### ISSUE TITLE
Can't connect to Helium

### ISSUE THREAD

**Issue by superivaj** [MaibornWolff/dcos-zeppelin#5]
Hi Sebastian,

I would like to add a new visualization to this package from Helium but the menu is empty. Is there anyway to enable it or is it not supported in this version?
![image](https://user-images.githubusercontent.com/25913368/41849542-36b14a60-7879-11e8-8c84-237a3a11a78d.png)

Best Regards,
Francisco

**Comment by swoehrl-mw** [comment]
Hi Francisco,

unfortunately we have not yet used Helium in Zeppelin so it is not specifically supported in this package. 
But pull requests are always welcome. Or, if you are not able to do that, if you can give me a list of necessary changes I can see about integrating them (though it might be a while).

Best regards,
Sebastian
