### ISSUE TITLE
zeppelin and secret

### ISSUE THREAD

**Issue by us3r** [MaibornWolff/dcos-zeppelin#6]
Can't install zeppelin on DC/OS EE with using secret for shiro.

Adding "zeppelin/shiro-conf" to the secret field is raising below error:

`Invalid JSON: /secrets/shiroconf/source.error.minLength`

```
# dcos security secrets list /zeppelin
- secret
- shiro-conf
- zeppelin-key
- zeppelin-pub
```
Where :
```
# dcos security secrets get /zeppelin/shiro-conf
[users]
admin = password1, admin
user1 = password2, role1, role2
user2 = password3, role3
user3 = password4, role2

[main]
securityManager.realm = $ldapRealm
(...)
```

**Comment by swoehrl-mw** [comment]
Thanks for reporting this. You uncovered a bug in the universe package (typo in mustache variables which leads to a faulty string substitution which leads to the secrets source field being empty). I will build a new version with a fix. In the meantime you can either use the previous version of the package (0.7.3-2.2.1) or deploy the app directly using one of the marathon definitions in this git repo.

**Comment by swoehrl-mw** [comment]
With https://github.com/mesosphere/universe/pull/1897 a new version has been released in the universe that fixes this bug.
